
# scripts that are called at very beginning, before repo cloning
init:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

services:
  chrome: stable

install:
  - pip install -r requirements.txt
script:
  - python --version
  - behave